project:
  type: book

book:
  title: "RStatsbook"
  author: "Andreas Busjahn"
  date: "2024-10-21"
  page-footer:
    left: |
      R Intro by Andreas Busjahn
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/abusjahn/RStatsbook/
  chapters:
    - index.qmd
    - RScripts/intro.qmd
    - RScripts/01_R101.qmd
    - RScripts/02_regex.qmd
    - RScripts/03_import.qmd
    - RScripts/pivot.qmd
    - RScripts/variableclassification.qmd
    - RScripts/visualize.qmd
    - RScripts/describe.qmd
    - RScripts/summarize.qmd
    # - flextable.qmd
    - RScripts/test2groups.qmd
    - RScripts/CovCor.qmd
    - RScripts/lm.qmd
    - RScripts/lm_interaction.qmd
    - RScripts/glm.qmd
    - RScripts/MLintro.qmd
    - RScripts/MCMC.qmd
    - RScripts/knn.qmd
    - RScripts/regressiontree.qmd
    - RScripts/xgboost.qmd
    - RScripts/PCA.qmd
    - RScripts/LDA.qmd
    - RScripts/cluster.qmd
    - RScripts/caret.qmd
    # - lmm-qmd
    # - summary.qmd
    # - references.qmd

bibliography: references.bib

format:
  # html:
  #   theme: cosmo
  pdf:
    latex-auto-install: true
    # latex-auto-install-force: true
    latex-auto-mk: true
    documentclass:  scrreprt #book
    papersize: a4
    code-block-bg: ffffdf
    # include-in-header:
      # \usepackage{graphbox}
      # \usepackage{wrapfig}
      # \usepackage{float}
  # word:
  #   template:

editor: visual
highlight-style: github

# execute:
#   output: asis
  