project:
  type: book

book:
  title: "RStatsbook"
  author: "Andreas Busjahn"
  date: "2025-04-06"
  page-footer:
    left: |
      R Intro by Andreas Busjahn
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/abusjahn/RStatsbook/
  chapters:
    - index.qmd
    - RScripts/intro.qmd
    - RScripts/01_R101.qmd
    - RScripts/02_regex.qmd
    - RScripts/03_import.qmd
    - RScripts/04-pivot.qmd
    - RScripts/05-visualize.qmd
    - RScripts/06-variableclassification.qmd
    - RScripts/08-summarize.qmd
    - RScripts/07-describe.qmd
    # - flextable.qmd
    - RScripts/09-test2groups.qmd
    - RScripts/10-CovCor.qmd
    - RScripts/11-lm.qmd
    - RScripts/12-lm_interaction.qmd
    - RScripts/13-glm.qmd
    - RScripts/14-MLintro.qmd
    - RScripts/15-MCMC.qmd
    - RScripts/16-knn.qmd
    - RScripts/17-regressiontree.qmd
    - RScripts/18-xgboost.qmd
    - RScripts/19-caret.qmd
    - RScripts/20-PCA.qmd
    - RScripts/21-LDA.qmd
    - RScripts/22-cluster.qmd
    # - lmm-qmd
    # - summary.qmd
    # - references.qmd

bibliography: references.bib

format:
  # html:
  #   theme: cosmo
  pdf:
    latex-auto-install: true
    # latex-auto-install-force: true
    latex-auto-mk: true
    documentclass:  scrreprt #book
    papersize: a4
    code-block-bg: ffffdf
    # include-in-header:
      # \usepackage{graphbox}
      # \usepackage{wrapfig}
      # \usepackage{float}
  # word:
  #   template:

editor: visual
highlight-style: github

# execute:
#   output: asis
  