project:
  type: book

book:
  title: "RStatsbook"
  author: "Andreas Busjahn"
  date: "2025-04-06"
  page-footer:
    left: |
      R Intro by Andreas Busjahn
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/abusjahn/RStatsbook/
  chapters:
    - index.qmd
    - RScripts/01_intro.qmd
    - RScripts/02_R101.qmd
    - RScripts/03_regex.qmd
    - RScripts/04_import.qmd
    - RScripts/05_pivot.qmd
    - RScripts/06_visualize.qmd
    - RScripts/07_variableclassification.qmd
    - RScripts/08_describe.qmd
    - RScripts/09_summarize.qmd
    # - flextable.qmd
    - RScripts/10_test2groups.qmd
    - RScripts/11_CovCor.qmd
    - RScripts/12_lm.qmd
    - RScripts/13_lm_interaction.qmd
    - RScripts/14_glm.qmd
    - RScripts/15_MLintro.qmd
    - RScripts/16_MCMC.qmd
    - RScripts/17_knn.qmd
    - RScripts/18_regressiontree.qmd
    - RScripts/19_xgboost.qmd
    - RScripts/20_caret.qmd
    - RScripts/21_PCA.qmd
    - RScripts/22_LDA.qmd
    - RScripts/23_cluster.qmd
    # - lmm-qmd
    # - summary.qmd
    # - references.qmd

bibliography: references.bib

format:
  # html:
  #   theme: cosmo
  pdf:
    latex-auto-install: true
    # latex-auto-install-force: true
    latex-auto-mk: true
    documentclass:  scrreprt #book
    papersize: a4
    code-block-bg: ffffdf
    # include-in-header:
      # \usepackage{graphbox}
      # \usepackage{wrapfig}
      # \usepackage{float}
  # word:
  #   template:

editor: visual
highlight-style: github

# execute:
#   output: asis
  