# Simple test statistics

```{r}
pacman::p_load(conflicted,plotrix,tidyverse, wrappedtools,
               coin,ggsignif, patchwork, ggbeeswarm,
               flextable)
#conflicted)
# conflict_prefer("filter", "dplyr")
load("data/bookdata1.RData")

```

## Quantitative measures with Gaussian distribution

```{r}
ggplot(rawdata,aes(x=Sex,y=`Size (cm)`))+
  geom_beeswarm(size=3)+
  stat_summary(color="red",size=1.2,alpha=.7, 
               fun.data="mean_se",fun.args=list(mult=2))+
  ylab("size (mean \u00B1 2*SEM)")

rawdata |> 
  group_by(Sex) |> 
summarize(MeanSE=meanse(`Size (cm)`),
          SD=sd(`Size (cm)`))

t.test(x = rawdata$`Size (cm)`[which(rawdata$Sex=="f")],
       y = rawdata$`Size (cm)`[which(rawdata$Sex=="m")])
tOut<-t.test(rawdata$`Size (cm)`~rawdata$Sex)
tOut$p.value

# equal variances assumption?
vartestOut<-var.test(rawdata$`Size (cm)`~rawdata$Sex)
vartestOut
# manual entry
t.test(rawdata$`Size (cm)`~rawdata$Sex,
              var.equal = vartestOut$p.value>.05)
# picked from test
t.test(rawdata$`Size (cm)`~rawdata$Sex,
       var.equal=var.test(
         rawdata$`Size (cm)`~rawdata$Sex)$p.value>.05)
#combined function
t_var_test(data = rawdata,
           formula = "`Size (cm)`~Sex",
           cutoff = .1)


print(c(mean(rawdata$`sysBP V0`,na.rm=T),
        mean(rawdata$`sysBP V2`,na.rm=T)))

t.test(rawdata$`sysBP V0`,
       rawdata$`sysBP V2`,
       alternative="greater", # x>y
       paired=TRUE)  #pairwise t-test, within subject
t.test(rawdata$`sysBP V0`,
       rawdata$`sysBP V2`,
       # alternative="greater", # x>y
       paired=T)$p.value/2  #pairwise t-test, within subject

t.test(rawdata$`Size (cm)`,mu = 173)

groupvars <- ColSeeker(namepattern = c("Sex","Test"))

compare2numvars(data = rawdata,dep_vars = gaussvars$names,
                indep_var = "Sex",gaussian = T,
                round_desc = 3,add_n = T, mark=T) |> 
  flextable() |> 
  set_table_properties(width=1, layout="autofit")
compare2numvars(data = rawdata,dep_vars = gaussvars$names,
                indep_var = "Testmedication",gaussian = T,
                round_desc = 4) |> 
  flextable() |> 
  set_table_properties(width=1, layout="autofit")


```

```{r}
#| output: asis
for(group_i in seq_len(groupvars$count)){
  resulttmp <- 
    compare2numvars(data = rawdata,
                    dep_vars = gaussvars$names,
                    indep_var = groupvars$names[group_i],gaussian = T)
  # print(resulttmp)
  flextable(resulttmp)  |> 
  set_table_properties(width=1, layout="autofit") |>
  flex2rmd() #|> print()
  cat("<br>\n\n")
  cat("\\newpage\n\n")
}
```

## Ordinal data

```{r}
ordvars$names
ggplot(rawdata,aes(`Ptt Lab`))+
  geom_density()
by(data = rawdata[[ordvars$index[1]]], 
   INDICES = rawdata$Sex,FUN = median_quart)

ggplot(rawdata,aes(Sex,`Ptt Lab`))+
  geom_boxplot()+
  geom_beeswarm(alpha=.5)
(uOut<-wilcox.test(
  rawdata[[ordvars$names[3]]]~rawdata$Sex,exact=F))
uOut$p.value
#  coin::wilcox_test
(uOut2<-wilcox_test(`Ptt Lab`~Sex,
                    data=rawdata))
pvalue(uOut2) #no list-object, but methods to extract infos like p
wilcox.test(`Ptt Lab`~Sex,exact=F,correct=F,
            data=rawdata)
wilcox.test(x=rawdata$`sysBP V0`,y=rawdata$`sysBP V2`,
            exact=FALSE,
            correct=TRUE,paired=TRUE)

compare2numvars(data = rawdata,dep_vars = ordvars$names,n = F,
                range = T,add_n = T,
                indep_var = "Sex",gaussian = F) |> 
  flextable() |> 
  set_table_properties(width=1, layout="autofit")
```

## Categorial data

```{r}
factvars$names
(crosstab<-table(rawdata$Sex,rawdata$Testmedication))
chisq.test(crosstab,simulate.p.value=T,B=10^5)  #empirical p-value

chisq.test(table(rawdata$Sex,rawdata$`NYHA V1`))  #based on table
chisq.test(x=rawdata$Sex,y=rawdata$`NYHA V1`,
           simulate.p.value=T,B=10^5)  #based on rawdata
fisher_out <- fisher.test(
  table(rawdata$Sex,rawdata$`NYHA V1`))  
fisher_out$p.value

(crosstab1<-table(rawdata$Sex,
                  rawdata$`Weight (kg)`<=
                    median(rawdata$`Weight (kg)`)))

(tabletestOut<-chisq.test(crosstab1,simulate.p.value=T,
                          B=10^5))
tabletestOut$p.value
tabletestOut$expected
tabletestOut$observed
tabletestOut$statistic
# if minimum(expected<5) then Fishers exact test
if(min(tabletestOut$expected)<5) {
  tabletestOut<-fisher.test(crosstab1)
}
tabletestOut$p.value 
# report_cat
groupvar <- "Testmedication"

compare2qualvars(rawdata,dep_vars = factvars$names[-1],
                 indep_var = groupvar,spacer = " ") |> 
  flextable() |> 
  align(~p==" ",j = 1,align = "center")
```
